version: '3.2'
services:
  proxy:
    build: ./proxy
    ports: 
      - "80:80"
      - "443:443"
    depends_on:
      - web

  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  web:
    image: passit/passit:stable
    command: bin/start.sh
    ports:
      - "8000:8080"
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/postgres
      SECRET_KEY: myscecretkeypasswordlol
      IS_DEBUG: 'False'
      EMAIL_URL: smtp+ssl://user:password@smtp.gmail.com:465
      DEFAULT_FROM_EMAIL: "passit@something.com"
      EMAIL_CONFIRMATION_HOST: "https://passit.local"
    depends_on:
      - db
